### ISSUE TITLE
Comments from testing

### ISSUE THREAD

**Issue by Mmintyyy** [cms-opendata-workshop/workshop-lesson-virtualmachine#1]
Time used to complete the lesson: 1 h 54 mins
I did not take time of separate sections, but I think that the estimates were pretty accurate.

### General
**Helpline**
- Mattermost links not working yet.

### Introduction
- It is not intuitive that "^" button at the bottom of the page brings you back to the front page and I was expecting to get to the top of the current page using the button. Using "<" instead as in the following pages could be more intuitive for the user.

### Hiring a hypervisor
- I was a bit confused by the fact that the "download" link leads to the Virtual Box download site, even though I had already downloaded the same file from the Setup page. At first I thought that I would need to download an additional file on this page.
- Typo: "recordin" -> "record on"

### Recruiting the labor force
- Same thing on this page as on the previous one, I had already downloaded the file
	
**Importing the image into VirtualBox**
- "By double clicking the downloaded file, VirtualBox imports the image with ready-to-run settings."
	○ This did not work for me, I had to Import manually in the program through File > Import Appliance…
- "Change the Network settings for adapter 2 from Host-only Adapter to NAT."
	○ This was a bit confusing to me, maybe the instructions could include a picture? Below a screenshot I took:

![Network-settings](https://user-images.githubusercontent.com/12005921/93067663-2bd95200-f684-11ea-8d5b-fe54f02d92f1.png)

**Key points**
- "To install the 2011 CMS VM, download the appropriate VM image, import it into VirtualBox and launch it."
	○ As version 1.5.3 should be used, its number could also be mentioned here -> "To install the 2011 CMS VM, download the appropriate VM image (version 1.5.3), import it into VirtualBox and launch it."
	○ It might be more convenient for the user, if the "download" link would open the download for the right VM image version (as in some previous links on this page) and not lead to the download page with several options
		

### Test and validate

**Know your VM**
- CernVM  CernVM File System links not working

**Run a simple demo for testing and validating**
- At this point I realized that my VM keyboard did not match my physical keyboard. To fix this, I had to go to the "Settings Manager > Keyboard > Layout" and unclick "Use system defaults", then choose the correct keyboard layout from the list which matched my computer model, then change the Keyboard layout to "Finnish"
- "do not worry, you will learn about all this stuff in a different lesson" -> link to the lesson is not working
- After running the command "vi Demo/DemoAnalyzer/demoanalyzer_cfg.py" the code file opens, there could be instructions to activate the insert mode by pressing "i" to able to write text
- Is there an easy way to copy paste code from the host to the VM?
	○ If yes, it could be instructed
	○ If not, it could be stated that the things need to be typed manually
- Add instructions on what to do after making the changes to the code
	○ Exit insert mode with esc button
	○ Save the file and exit by typing ":wq"
- "and make sure the cms-opendata-conddb.cern.ch directory has actually expanded in your VM. One way of doing this is executing:
Bash
ls -l
ls -l /cvmfs/"
	○ What should you expect to see as an output after this is expanding has been successful? This was a bit unclear to me, so I think that the expected Output could be included in the instructions

**Comment by caredg** [comment]
Hi @Mmintyyy thanks for the feedback.  I will take care of them soon.  Some things, like some broken links are ok, but need to become available in the next few days.

**Comment by caredg** [comment]
> Time used to complete the lesson: 1 h 54 mins
> I did not take time of separate sections, but I think that the estimates were pretty accurate.
> 
> ### General
> **Helpline**
> 
> * Mattermost links not working yet.
> 
> ### Introduction
> * It is not intuitive that "^" button at the bottom of the page brings you back to the front page and I was expecting to get to the top of the current page using the button. Using "<" instead as in the following pages could be more intuitive for the user.
> 
> ### Hiring a hypervisor
> * I was a bit confused by the fact that the "download" link leads to the Virtual Box download site, even though I had already downloaded the same file from the Setup page. At first I thought that I would need to download an additional file on this page.
> * Typo: "recordin" -> "record on"
> 
> ### Recruiting the labor force
> * Same thing on this page as on the previous one, I had already downloaded the file
> 
> **Importing the image into VirtualBox**
> 
> * "By double clicking the downloaded file, VirtualBox imports the image with ready-to-run settings."
>   ○ This did not work for me, I had to Import manually in the program through File > Import Appliance…
> * "Change the Network settings for adapter 2 from Host-only Adapter to NAT."
>   ○ This was a bit confusing to me, maybe the instructions could include a picture? Below a screenshot I took:
> 
> ![Network-settings](https://user-images.githubusercontent.com/12005921/93067663-2bd95200-f684-11ea-8d5b-fe54f02d92f1.png)
> 
> **Key points**
> 
> * "To install the 2011 CMS VM, download the appropriate VM image, import it into VirtualBox and launch it."
>   ○ As version 1.5.3 should be used, its number could also be mentioned here -> "To install the 2011 CMS VM, download the appropriate VM image (version 1.5.3), import it into VirtualBox and launch it."
>   ○ It might be more convenient for the user, if the "download" link would open the download for the right VM image version (as in some previous links on this page) and not lead to the download page with several options
> 
> ### Test and validate
> **Know your VM**
> 
> * CernVM  CernVM File System links not working
> 
> **Run a simple demo for testing and validating**
> 
> * At this point I realized that my VM keyboard did not match my physical keyboard. To fix this, I had to go to the "Settings Manager > Keyboard > Layout" and unclick "Use system defaults", then choose the correct keyboard layout from the list which matched my computer model, then change the Keyboard layout to "Finnish"
> * "do not worry, you will learn about all this stuff in a different lesson" -> link to the lesson is not working
> * After running the command "vi Demo/DemoAnalyzer/demoanalyzer_cfg.py" the code file opens, there could be instructions to activate the insert mode by pressing "i" to able to write text
> * Is there an easy way to copy paste code from the host to the VM?
>   ○ If yes, it could be instructed
>   ○ If not, it could be stated that the things need to be typed manually
> * Add instructions on what to do after making the changes to the code
>   ○ Exit insert mode with esc button
>   ○ Save the file and exit by typing ":wq"
> * "and make sure the cms-opendata-conddb.cern.ch directory has actually expanded in your VM. One way of doing this is executing:
>   Bash
>   ls -l
>   ls -l /cvmfs/"
>   ○ What should you expect to see as an output after this is expanding has been successful? This was a bit unclear to me, so I think that the expected Output could be included in the instructions

These will go in the next push
- I think the links are fixed.
- Unfortunately the "^" is a carpentry thing.
- I changed the setup instructions so they don't create confusion.
- Made clear about the import appliance option
- Added the NAT image (thanks for the screenshot)
- Updated key points for vm image and specific link
- CernVM CernVM File System link working for me.... (?)
- Now that the lesson exists, the link to the cmssw lesson is working.
- I am not sure I should give instructions specific to the vi editor (i do mention a chetsheet that can be used)
- No easy solution for the clipboard problem.  I added a warning and a hint to solve that problem
- Added a note on additional editors on the VM like emacs or nano
- Added output to check for /cvmfs directories
