### ISSUE TITLE
Add a mention for cvmfs and brilcalc? 

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-virtualmachine#2]
The docker tutorial goes in details for `cvmfs` and `brilcalc` in https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/04-cvmfs-and-brilcalc/index.html
`cvmfs` is already accessible in the VM, so no need for any installation instructions. However, in order for the VM and docker users to get to the same level through the pre-exercises, it would be useful to add in this tutorial the `brilcalc` getting started e.g

```
export PATH=$HOME/.local/bin:/cvmfs/cms-bril.cern.ch/brilconda/bin:$PATH
pip install --user brilws

brilcalc --version
brilcalc lumi -c web -r 160431
```

**Comment by caredg** [comment]
I think the luminosity demo will cove these instructions.  The important thing for the docker is to have installed the cvmfs client.  But just dumping the brilcal, without any introduction, seems to me it will be confusing.  I do not think there is need to do it here.
