### ISSUE TITLE
Add instructions for sharing volumes or copying files from VM

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-virtualmachine#3]
Docker instructions explain how to share volume and copy files to and from the docker image. It would be good to have this for VM users as well.

e.g. from VM to  lxplus (and similarly to any other domain)

`scp myfileonVM.csv username@lxplus.cern.ch:myfilefromVM.csv
`

**Comment by caredg** [comment]
I have added this option
