### ISSUE TITLE
From the mattermost chat: Mac settings for VM

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-virtualmachine#5]
From [the mattermost chat](https://mattermost.web.cern.ch/cmsopendatatheo/channels/vm-pre-exercise):

>  I am unable to install the OpenData image with an error "|Result Code: | NS_ERROR_INVALID_ARG (0x80070057)|" 
> Any ideas of how to solve this?  I am on MacOS Catalina and using VirtualBox v 6.1.
...
> Okay, I got the VM to work.  There are some changes to Mac Settings required (Privacy and Accessibility in case anyone else has the same problem).  However, now I have an error "Unable to mount cvmfs root filesystem."  

Not clear, however, if the mount error message is due to the VM itself or something that the user did in addition (by mistake or because of unclear instructions).

Someone with MacOS Catalina should check the VM download and start.

**Comment by caredg** [comment]
close as it is an older version
